# Generated by Django 3.0.7 on 2020-06-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200616_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
