# Generated by Django 3.0.7 on 2020-07-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_content_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='color',
            field=models.CharField(blank=True, choices=[('mlt', 'Multicolors'), ('grs', 'Grayscale'), ('trs', 'Transparent'), ('rd', 'Red'), ('or', 'Orange'), ('yl', 'Yellow'), ('grn', 'Green'), ('tqs', 'Turquoise'), ('bl', 'Blue'), ('llc', 'Lilac'), ('pk', 'Pink'), ('wh', 'White'), ('gry', 'Gray'), ('blk', 'Black'), ('br', 'Brown')], default='mlt', max_length=3),
        ),
        migrations.AlterField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
