# Generated by Django 3.0.7 on 2020-07-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_content_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='public_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
