# Generated by Django 3.0.7 on 2020-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('cr', 'Creator'), ('vw', 'Viewer'), ('ot', 'Other')], default='vw', max_length=2),
        ),
    ]
