# Generated by Django 3.0.7 on 2020-06-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20200622_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, default='https://i.ya-webdesign.com/images/default-image-png-1.png', max_length=500),
        ),
    ]
