# Generated by Django 3.0.7 on 2020-06-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('isAnswered', models.BooleanField(default=False)),
                ('isSolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('cr', 'Creator'), ('vw', 'Viewer'), ('ot', 'Other')], default='cr', max_length=2)),
            ],
        ),
    ]
